apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Ваш тестовый репозиторий
    repoURL: https://github.com/KatyaPikta/argocd_adoption.git
    targetRevision: HEAD
    # Путь к папке с ApplicationSet'ами (или Application'ами)
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
